chatformat:
  default: '&7[&r%vault_rankprefix%&7] &f%player_name%&7: &r%message%'
  perGroup:
    enabled: true
    groups:
      default: '&7[&a%vault_rankprefix%&7] &f%player_name%&7: &r%message%'
      player: '&7[&a%vault_rankprefix%&7] &f%player_name%&7: &r%message%'
      admin: '&7[&c%vault_rankprefix%&7] &c%player_name%&7: &r%message%'
      owner: '&7[&r%vault_rankprefix%&7] &4%player_name%&7: &r%message%'