name: ChatFormat
version: 1.0.0
api-version: 1.13
author: thelegend
main: com.zorbeytorunoglu.chatformat.CH
depend:
  - kLib
  - PlaceholderAPI
commands:
  chatformat:
    description: Command to reload configurations
permissions:
  chatformat.reload:
    description: Permission to reload the configurations
    default: op
  chatformat.coloredchat:
    description: Permission for players to use color codes
    default: op